# LAB04.3 - Ansible Playbooks - Templates

In this lab we start to use templates!

### TASK 1
- Rewrite your playbook `motd.yml` without using the `copy` module, but rather using the `template` module.
- Use a jinja2 template file called `motd.j2` which uses the variable `motd_content`.

### TASK 2
- Improve the template `motd.j2` by adding the default ip address of the server to the template. 
- Add the installed operating system to the motd file aswell.

### TASK 3 (Advanced)
- Create a variable `users` like the following:
```
users:
  - name: jim
    job: apprentice
  - name: sabrina
    job: chief
  - name: hans
    job: engineer
  - name: eveline
    job: chief
  - name: santos
```
- Put the variable in an appropiate place of your choosing
- Create a playbook `userplay.yml` doing the following on node2:
- Create a file /etc/employees.txt with the content below by using the ansible module `template`:
```
<name_of_user> <job_of_user>
```
- There should be a entry in the file /etc/employees.txt for each user in the variable "users" (use a for-loop in the template)
- If a user has no job specified, use "housekeeper" (have a look at "playbooks_filters" in the online docs)
- On node1 do create a group for every different job in the variable `user`.
- Create a user on node1 for every user entry in the "users" variable. Ensure that this user is also in the group with the same name as his job.
- BONUS: set the loginshell to /bin/zsh.
- BONUS: if (and only if) the user is Santos, disable login. (use a if/else statement in the template)

## Solutions

.Solution 1
[%collapsible]
====
Create the file `motd.j2` with the following one liner:
[shell]
----
$ cat motd.j2
{{ motd_content }}
----
Edit your `motd.yml` playbook to use the file `motd.j2`:
[shell]
----
$ cat motd.yml 
---
- hosts: all
  become: yes
  tasks:
    - name: set content of /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
----
Run the playbook again.
[shell]
----
$ ansible-playbook motd.yml -l node1,node2
----
====

.Solution 2
[%collapsible]
====
Add IP and OS to `motd.j2`:
[shell]
----
$ cat motd.j2
{{ motd_content }}
IP ADDRESS:	{{ ansible_default_ipv4.address }}
OS:		{{ ansible_os_family }}

----
Rerun the playbook and login to a node to check if the text has been changed accordingly:
[shell]
----
$ ansible-playbook motd.yml -l node1,node2
$ ssh -l ansible <node1-ip>
[3~Last login: Fri Nov  1 14:39:53 2019 from 5-102-146-174.cust.cloudscale.ch
This is node2

IP ADDRESS:     5.102.146.204
OS:             RedHat
[ansible@node2 ~]$ 
----
====

.Solution 3
[%collapsible]
====
Since you are an expert already no detailed solution provided. :-) Discuss your solution with your lab-neighbour and your teacher.
====
