# LAB04.2 - Ansible Playbooks - Variables and loops

In this lab we'll get used to writing and running ansible playbooks.

### TASK 1
- In your playbook `webserver.yml` you have two tasks for starting and enabling `httpd` and `firewalld`. Merge these 2 tasks
  into one.

[TIP]
====
Remember `loop:` or `with_items:`
====

### TASK 2
- In your playbook `webserver.yml`, ensure that that the yum package `firewalld` is installed. Do the installation of `httpd` and `firewalld` in one task. Do you really need to use a loop? Have a look at the description of the ansible module `yum`.

### TASK 3
- Write a new playbook `motd.yml` which sets the content of `/etc/motd` on all servers to a custom text. Use
  the variable `motd_content` and the `copy` module with the option `content` containing the variable. 

### TASK 4
- Using the command line, overwrite the content of `motd` by providing the variable `motd_content` with a different value.
- Modify the content again, but use a `vars.yml` file.

### TASK 5
- Set the value of `motd_content` using `group_vars` for node1 and `host_vars` for node 2. 
- Make sure you remove the variable definition in `motd.yml`. Reason being it will have a higher priority. 
- Limit the run to node1 and node2. 

[TIP]
====
Think about where you have to create the folders for your host and group variables
====

## Solutions

.Solution 1
[%collapsible]
=====
Delete the 2 tasks "start and enable [httpd,firewalld]". Add a new task with the following content:
[shell]
----
- name: start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - firewalld
----

[NOTE]
====
Make sure your indentations are correct!
Older ansible-versions don't know the keyword "loop" yet, use "with_items" instead.
====
=====

.Solution 2
====
[shell]
----
...
tasks:
    - name: install httpd
      yum:
        name:
          - httpd
          - firewalld
        state: installed
...
----
https://docs.ansible.com/ansible/latest/modules/yum_module.html#yum-module
====

.Solution 3
[%collapsible]
====
Content of modt.yml:
[shell]
----
---
- hosts: all
  become: yes
  vars:
    motd_content: "Thi5 1s some r3ally stR4nge teXT!\n"
  tasks:
    - name: set content of /etc/motd
      copy:
        dest: /etc/motd
        content: "{{ motd_content }}"
----
[shell]
----
$ ansible-playbook motd.yml
----
Take a look at what your playbook just did:
[shell]
----
$ ssh -l ansible <node1-ip>
Last login: Fri Nov  1 14:16:08 2019 from 5-102-146-174.cust.cloudscale.ch
Thi5 1s some r3ally stR4nge teXT! # <-- it worked!
[ansible@node1 ~]$ 
----
====

.Solution 4
[%collapsible]
====
[shell]
----
$ ansible-playbook motd.yml --extra-vars motd_content="0th3r_5trang3_TExt"

$ ssh -l ansible <node1-ip>
Last login: Fri Nov  1 14:18:52 2019 from 5-102-146-174.cust.cloudscale.ch
0th3r_5trang3_TExt # <-- it worked
[ansible@node1 ~]$ 
----
[shell]
----
$ cat vars.yml
---
motd_content: "st1ll m0r3 str4ng3 TexT!"
$ ansible-playbook motd.yml --extra-vars @vars.yml
----
Login via SSH again and check if the new text was set.
====

.Solution 5
[%collapsible]
====
Your `motd.yml` should look something like this:
[shell]
----
---
- hosts: all
  become: yes
  tasks:
    - name: set content of /etc/motd
      copy:
        dest: /etc/motd
        content: "{{ motd_content }}"
----
After creating the new directories and files you should have something similar to this:
[shell]
----
$ cat inventory/group_vars/web.yml 
---
motd_content: "This is a webserver\n"
$ cat inventory/host_vars/node2.yml 
---
motd_content: "This is node2\n"
----
Run your playbook and check if the text was changed accordingly on the two nodes:
[shell]
----
$ ansible-playbook motd.yml -l node1,node2

$ ssh -l ansible <node1-ip>
Last login: Fri Nov  1 14:26:37 2019 from 5-102-146-174.cust.cloudscale.ch
This is node2 # <-- worked like a charm
[ansible@node2 ~]$
----
====
