# LAB07 - Ansible vault

In this lab we are going to practice encryption in ansible playbooks. It assumes your working directory is always `/home/ansible/techlab/`.

### Task 1
- Create a simple playbook called `secretservice.yml` which creates a file `MI6` in the `/etc/` directory on node1 and node2. Use the `template` module and a template named `nsa.j2`. Don't encrypt anything yet and use the inventory hosts from the earlier labs.

The content of the file `MI6` should be:
[shell]
----
username: jamesbond
password: miss_moneypenny
----

- Run the playbook and check if the file `/etc/MI6` has been deployed on the nodes.

### TASK 2
- Make the playbook `secretservice.yml` use a variable file named `secret_vars.yml` with the content:
[shell]
----
var_username: jamesbond
var_password: miss_moneypenny
----

- Rewrite the `nsa.j2` template to use the variables from the `secret_vars.yml` file. Nothing is encrypted yet.

- Make playbook `secretservice.yml` use the variable file `secret_vars.yml`.

- Rerun the playbook and remember nothing has been encrypted yet.

### TASK 3

- Encrypt the `secret_vars.yml` file by using `ansible-vault` with the password _Dr.NO!_ provided on the commandline.
- See if the file was encrypted
- Decrypt the file, so that it humanreadable again

- Create a file named `vaultpassword` containing the unencrypted string "goldfinger".
- Encrypt the file by using the file `vaultpassword`

[TIP]
====
You don't have to set a label.
====

- Rerun the playbook providing the vaultpassword file. 

### TASK 4
- Configure your environment to always use the `vaultpassword` file as the vault file.

- Rerun the playbook without providing the password or the passwordfile in the commandline.

### TASK 5
- Decrypt the file `secret_vars.yml`.

- Encrypt the values of `username` and `password` and put them into the `secret_vars.yml` file.

### TASK 6
- Remove the `/etc/MI6` file on the nodes using an ad-hoc command.

### TASK 7
- Encrypt another file secret_vars2.yml. Ensure its encrypted with your password
- Change the encryption of the file: encrpyt it with another password provided at the commandline. (Hint not by decrypting & reencrypting but with using `rekey`)
- try using the option --vault-id and try using --ask-vaut-pass

### TASK 8
- What can you do, to avoid ansible to print out sensitive data ar runtime? (see docs.ansible.com)

## Solutions
.Solution 1
[%collapsible]
====
[shell]
----
$ cat nsa.j2 
username: jamesbond
password: miss_moneypenny

$ cat secretservice.yml 
---
- hosts: node1, node2
  become: yes
  tasks:
    - name: put template
      template:
        src: nsa.j2
        dest: /etc/MI6

$ ansible-playbook secretservice.yml -i inventory/hosts  
----
====

.Solution 2
[%collapsible]
====
[shell]
----
$ cat secret_vars.yml 
---
var_username: jamesbond
var_password: miss_moneypenny

$ cat nsa.j2 
username: {{ var_username }}
password: {{ var_password }}

$ cat secretservice.yml 
---
- hosts: node1, node2
  become: yes
  vars_files:
    - secret_vars.yml
  tasks:
    - name: put template
      template:
        src: nsa.j2
        dest: /etc/MI6

$ ansible-playbook secretservice.yml -i inventoryhosts
----
====

.Solution 3
[%collapsible]
====
[shell]
----
$ cat vaultpassword 
goldfinger

$ ansible-vault encrypt secret_vars.yml --vault-id vaultpassword
Encryption successful

$ ansible-playbook secretservice.yml -i inventory/hosts --vault-id vaultpassword
----
====

.Solution 4
[%collapsible]
====
Make sure you recieve the following output in your terminal:
[shell]
----
$ grep ^vault /home/ansible/techlab/ansible.cfg 
vault_password_file = /home/ansible/techlab/vaultpassword

$ ansible-playbook secretservice.yml -i inventory/hosts
----
====

.Solution 5
[%collapsible]
====
[shell]
----
$ ansible-vault decrypt secret_vars.yml

$ echo "---" > secret_vars.yml; ansible-vault encrypt_string jamesbond -n var_username >> secret_vars.yml; ansible-vault encrypt_string miss_moneypenny -n var_password >> secret_vars.yml

$ cat secret_vars.yml 
---
var_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65336662623334393265373462616231323635623034653534393861666637333232383438393534
          3264376362633566313337333835313832376566343362330a636639346263323961636232306134
          35393462343935653031353430636666326232343565383330386339646436376265316264376366
          3336326566663033300a396666316461356336313564323236333138623465373439343032333930
          6664
var_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33366638383438373238333335663933323663326630356564626139323135306563343335613331
          6534373239393234366431656234386232373331316634660a646665303838636465303638316366
          63393034643639393764666634303338636130326164366339303634643264646235323637326661
          3633393039613263390a653062383834323661386661313733393662393935663263633565396133
          3931

$ ansible-playbook secretservice.yml -i inventory/hosts
----
====

.Solution 6
[%collapsible]
=====
[shell]
----
$ ansible node1,node2 -i inventory/hosts -b -a "rm /etc/MI6"
----
[NOTE]
====
Note that the `command` module is the `default` module and therefore has not to be specified here.
====
=====

.Solution 7
[%collapsible]
====
[shell]
----
$ ansible-vault rekey secret_vars2.yml --vault-id @prompt

$ ansible-playbook secretservice.yml -i inventory/hosts
----
====

.Solution 8
[%collapsible]
====
[shell]
----
no_log: true
----
see https://docs.ansible.com/ansible/devel/reference_appendices/logging.html
and https://docs.ansible.com/ansible/devel/reference_appendices/faq.html#keep-secret-data
====
