# LAB04 - Ansible Playbooks

In this lab we'll get used to writing and running ansible playbooks.

### Task 1
Create a playbook `webserver.yml` which does the following:

- Install `httpd` on the nodes in the `web` group.
- Start `httpd` and ensure the service starts on boot. Ensure that the firewall is also started and enabled.
- Ensure port 80 is open on the firewall.

[TIP]
====
 Check what the options "immediate" and "permanent" of the service module mean and do.
====

- Run the playbook. After completion test if the `httpd.service` is running and enabled on node1.

### TASK 2
- Create a folder `/home/ansible/techlab/inventory` and move your inventory-file `hosts` there.
- Configure ansible to use `/home/ansible/techlab/inventory/hosts` as the default inventory. Do this using a configuration file in the `/home/ansible/techlab/` directory. 
- Run the playbook again without using the `-i` flag to see if the configuration works.

### TASK 3
- In your playbook you have two tasks for starting and enabling `httpd` and `firewalld`. Merge these 2 tasks
  into one.

[TIP]
====
Remember `loop:` or the deprecated `with_items:`?
====

### TASK 4
- Write a new playbook `motd.yml` which sets the content of `/etc/motd` on all servers to a custom text. Use
  the variable `motd_content` and the `copy` module with the option `content` containing the variable. 

### TASK 5
- Using the command line, overwrite the content of `motd` by providing the variable `motd_content` with a different value.
- Modify the content again, but use a `vars.yml` file.

### TASK 6
- Set the `motd_content` from task 4 using `group_vars` for node1 and `host_vars` for node 2. 
- Make sure you remove the variable definition in `motd.yml`. Reason being it will have a higher priority. 
- Limit the run to node1 and node2. 

[TIP]
====
Think about where you have to create the folders for your host and group variables
====

### TASK 7
- Rewrite your playbook without using the `copy` module, but rather using the `template` module.
- Use a jinja2 template file called `motd.j2` which uses the variable `motd_content`.

### TASK 8
- Improve the template from task 7 by adding the default ip address of the server to the template. 
- Add the installed operating system to the motd file aswell.

## Solutions

.Solution 1
[%collapsible]
====
Below is a possible solution for your playbook: 

[shell]
----
---
- hosts: web
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: open firewall for http
      firewalld:
       service: http
       state: enabled
       permanent: yes
       immediate: yes
----

Run your playbook with:

[shell]
----
$ ansible-playbook -i hosts webserver.yml
----

Check `httpd.service` on node 1:

[shell]
----
$ systemctl status httpd.service 
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-11-01 13:44:25 CET; 2min 41s ago
     Docs: man:httpd(8)
...
...
====

.Solution 2
[%collapsible]
====
Copy the default ansible.cfg to your directory:
[shell]
----
$ mkdir /home/ansible/techlab/inventory
$ mv /home/ansible/techlab/hosts /home/ansible/techlab/inventory
$ cp /etc/ansible/ansible.cfg /home/ansible/techlab/
----

Edit your `ansible.cfg` file. Uncomment and edit the first "inventory" entry to:
[shell]
----
...
[defaults]
# some basic default values...
inventory      = /home/ansible/techlab/inventory/hosts # <-- edit this line
#library        = /usr/share/my_modules/
...
----

[shell]
----
$ ansible-playbook webserver.yml
PLAY [web] ***********************************************************************

TASK [Gathering Facts] ***********************************************************
ok: [node1]

TASK [install httpd] *************************************************************
ok: [node1]
...
----
====

.Solution 3
[%collapsible]
=====
Delete the 2 tasks "start and enable [httpd,firewalld]". Add a new task with the following content:
[shell]
----
- name: start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - firewalld
----

[NOTE]
====
Make sure your indentations are correct!
Older ansible-versions don't know the keyword "loop" yet, use "with_items" instead.
====
=====

.Solution 4
[%collapsible]
====
Content of modt.yml:
[shell]
----
---
- hosts: all
  become: yes
  vars:
    motd_content: "Thi5 1s some r3ally stR4nge teXT!\n"
  tasks:
    - name: set content of /etc/motd
      copy:
        dest: /etc/motd
        content: "{{ motd_content }}"
----
[shell]
----
$ ansible-playbook motd.yml
----
Take a look at what your playbook just did:
[shell]
----
$ ssh -l ansible <node1-ip>
Last login: Fri Nov  1 14:16:08 2019 from 5-102-146-174.cust.cloudscale.ch
Thi5 1s some r3ally stR4nge teXT! # <-- it worked!
[ansible@node1 ~]$ 
----
====

.Solution 5
[%collapsible]
====
[shell]
----
$ ansible-playbook motd.yml --extra-vars motd_content="0th3r_5trang3_TExt"

$ ssh -l ansible <node1-ip>
Last login: Fri Nov  1 14:18:52 2019 from 5-102-146-174.cust.cloudscale.ch
0th3r_5trang3_TExt # <-- it worked
[ansible@node1 ~]$ 
----
[shell]
----
$ cat vars.yml
---
motd_content: "st1ll m0r3 str4ng3 TexT!"
$ ansible-playbook motd.yml --extra-vars @vars.yml
----
Login via SSH again and check if the new text was set.
====

.Solution 6
[%collapsible]
====
Your `motd.yml` should look something like this:
[shell]
----
---
- hosts: all
  become: yes
  tasks:
    - name: set content of /etc/motd
      copy:
        dest: /etc/motd
        content: "{{ motd_content }}"
----
After creating the new directories and files you should have something similar to this:
[shell]
----
$ cat inventory/group_vars/web.yml 
---
motd_content: "This is a webserver\n"
$ cat inventory/host_vars/node2.yml 
---
motd_content: "This is node2\n"
----
Run your playbook and check if the text was changed accordingly on the two nodes:
[shell]
----
$ ansible-playbook motd.yml -l node1,node2

$ ssh -l ansible <node1-ip>
Last login: Fri Nov  1 14:26:37 2019 from 5-102-146-174.cust.cloudscale.ch
This is node2 # <-- worked like a charm
[ansible@node2 ~]$
----
====

.Solution 7
[%collapsible]
====
Create the file `motd.j2` with the following one liner:
[shell]
----
$ cat motd.j2
{{ motd_content }}
----
Edit your `motd.yml` playbook to something like this:
[shell]
----
$ cat motd.yml 
---
- hosts: all
  become: yes
  tasks:
    - name: set content of /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
----
Run the playbook again.
[shell]
----
$ ansible-playbook motd.yml -l node1,node2
----
====

.Solution 8
[%collapsible]
====
Add IP and OS to `motd.j2`:
[shell]
----
$ cat motd.j2
{{ motd_content }}
IP ADDRESS:	{{ ansible_default_ipv4.address }}
OS:		{{ ansible_os_family }}

----
Rerun the playbook and login to a node to check if the text has been changed accordingly:
[shell]
----
$ ansible-playbook motd.yml -l node1,node2
$ ssh -l ansible <node1-ip>
[3~Last login: Fri Nov  1 14:39:53 2019 from 5-102-146-174.cust.cloudscale.ch
This is node2

IP ADDRESS:     5.102.146.204
OS:             RedHat
[ansible@node2 ~]$ 
----
====
