# LAB01 - Setting up Ansible & your environment

During this lab you will configure ansible. You will be able to use ansible on the controller-node and run
your first commands on the ansible-nodes.

You have the IPs of the controller host and managemeble nodes. (given by your instructor). The controller host is where you execute Ansible from and the nodes represent the machines you like to manage.

To make it as easier for inexperienced users we installed an editor and terminal accessible with your browser:

## Open your Browser

Copy and paste the following URL and replace `<controller-ip>` with the IP of your controller host:

----
https://<dnsname>
----

Login using the following username and password:

----
username: ansible
password: << web password >>
----
After a successful login you should see an editor similar to _visual studio code_ in your browser. In the navigation bar you can open "Terminal" or press `ctrl-shift-^` to open a terminal. 
Do this now and then continue with the installation of Ansible.

### TASK 1
- Install all packages needed to use ansible on the controller.

[TIP]
====
Use `sudo -s` to elevate your privilege to that of `root`. The `-s` parameter keeps you in your current
working directory.
====

- Test if you can connect to the nodes from your controller using SSH. Use their public IPs you received from
  your instructor
- Make sure python is installed on your nodes before continuing with the lab.

### TASK 2
- Create a SSH-keypair for the `ansible` user on the `controller`. 
- Enable SSH-key login for the `ansible` user on all nodes and the controller by distributing the SSH-public key.
- Test the login on the nodes.

### TASK 3
- Create an inventory `hosts` file in your working directory with your public IPs:

[ini]
----  
[tower]
controller ansible_host=<your-controller-ip>

[web]
node1 ansible_host=<your-node1-ip>

[db]
node2 ansible_host=<your-node2-ip>
----  

[NOTE]
====
You're default working directory is at `/home/ansible/techlab`. You can switch your workspace under "File/Open
Workspace" and using the drop down menu.
====

- Check if ansible is ready using the `ping` module to ping all hosts in your inventory  

### TASK 4
- Configure the `ansible` user to have root privilege on all hosts in your inventory file. Also enable login
  without a password for this user.
- Test the functionality by running `sudo -v` as user `ansible` on all nodes.

## Solutions
.Solution 1
[%collapsible]
====
Installing ansible with root privileges:
[shell]
----
# yum -y install ansible 
----

Opening a SSH connection:  
[shell]
----
$ ssh -l ansible node1
----
- Enter "yes" when prompted if your want to continue connecting
- Copy paste your SSH-password you received from your instructor when prompted and hit return

On the nodes:  
[shell]
----
$ which python # (or which python3)
/usr/bin/python
----
====

.Solution 2
[%collapsible]
=====
[shell]
----
$ ssh-keygen #(no passphrase, just hit enter until the end)  
$ ssh-copy-id <node-ip>
----
Follow the prompt and enter the `ansible` user password you received from your instructor:

[NOTE]
====
Don't forget your controller and the second node.
====

[shell]
----
usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
The authenticity of host '5.102.146.128 (5.102.146.128)' can't be established.
ECDSA key fingerprint is SHA256:5PmNPnSzE2IS309kJ8fAKrAjk0/NZT91qC4zQo0Vwiw.
ECDSA key fingerprint is MD5:43:5f:9c:e1:ad:b5:76:a1:fa:5d:09:9c:be:5d:c2:7e.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
ansible@5.102.146.128's password: 

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh '5.102.146.128'"
and check to make sure that only the key(s) you wanted were added.
----
Test it by running the ssh command executed on that node:
[shell]
----
$ ssh <node-ip> hostname
[yourusernamehere]-node1
----
=====

.Solution 3
[%collapsible]
====
[shell]
----
$ ansible all -i hosts -m ping
5.102.146.128 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "ping": "pong"
}
...
...
----
====

.Solution 4
[%collapsible]
=====
Create a line in `/etc/sudoers` similar to the one for the `%wheel` group on all nodes.  

[shell]
----
$ ssh -l ansible <node-ip>
$ sudo -i
# grep wheel /etc/sudoers
## Allows people in group wheel to run all commands
%wheel  ALL=(ALL)       ALL
# %wheel        ALL=(ALL)       NOPASSWD: ALL

# echo 'ansible ALL=(ALL)   NOPASSWD: ALL' >> /etc/sudoers
----
Check if `ansible` user has root privileges:
[shell]
----
sudo -v
----

[NOTE]
====
Note that you cannot do this using ansible yet. The reason being you need root privileges and we are just setting this up right now.  
====
=====
