# LAB05.1 - Ansible Roles

During this lab we'll learn how to write and use ansible roles.

### Task 1
- Create a directory `roles` in your techlab folder.
- Configure your ansible environment to use the `roles` folder as source for roles.

### TASK 2
Write a `httpd` role in your new `roles` folder which does the following:

- Install `httpd`,  start its service and enable it to run on boot. 
- Install `firewalld` and allow traffic for the services `http` and `https`.

### TASK 3
- Modify your playbook `webserver.yml` from the earlier labs to use your new `httpd` role. It should be run on all hosts in the `web` group. 
- Run your playbook  and check if everything went as expected.

### TASK 4
- Create a new role called `base`. It's `main.yml` task file in the tasks/ folder should import the following taskfiles:
[.result]
====
* `motd.yml`:
  ** Use the template `motd.j2` from the labs before to create the file `/etc/motd`. Remember to move the template to the correct location in the `roles` folder
* `packages.yml` which has to install:
  ** firewalld
  ** yum-utils
  ** dos2unix
  ** emacs
  ** vim
====

- Write a `prod.yml` playbook which:
** Applies the `base` role to all servers
** Only applies the `webserver` role to the group `web`

### TASK 5
- Rewrite the `httpd` role to apply the `base` role each time it is used in a playbook. ("Dependency")
- Remove the play to run `base` role on all hosts in the `prod.yml` playbook. Run the playbook and see if role `base` was applied on hosts in the `web` group as well.

## Solutions

.Solution 1
[%collapsible]
====
[shell]
----
$ mkdir roles
$ grep roles_path ansible.cfg 
roles_path    = /etc/ansible/roles:/usr/share/ansible/roles:/home/ansible/techlab/roles
----
====

.Solution 2
[%collapsible]
====
[shell]
----
$ ansible-galaxy init roles/httpd

$ cat roles/httpd/tasks/main.yml 
---
# tasks file for httpd
- name: install packaged
  yum:
    name:
      - httpd
      - firewalld
    state: installed
- name: start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - firewalld
- name: open firewall for http and https
  firewalld:
    service: "{{ item }}"
    state: enabled
    immediate: yes
    permanent: true
  with_items:
    - http
    - https
----
====

.Solution 3
[%collapsible]
====
[shell]
----
$ cat webserver.yml 
---
- hosts: web
  become: yes
  roles:
    - httpd

$ ansible-playbook webserver.yml
----
====

.Solution 4
[%collapsible]
=====
[shell]
----
$ ansible-galaxy init roles/base;

$ cat roles/base/defaults/main.yml 
---
# defaults file for base
motd_content: "This is a server\n"

$ ls roles/base/tasks/
main.yml      motd.yml      packages.yml  

$ cat roles/base/tasks/motd.yml 
---
- name: put motd template
  template:
    src: templates/motd.j2

$ cat roles/base/templates/motd.j2 
{{ motd_content }}
IP ADDRESS:	{{ ansible_default_ipv4.address }}
OS:		{{ ansible_os_family }}    dest: /etc/motd

$ cat roles/base/tasks/packages.yml 
---
- name: install packages
  yum:
    name:
      - firewalld
      - yum-utils
      - dos2unix
      - emacs
      - vim 
    state: installed

$ cat roles/base/tasks/main.yml 
---
# tasks file for base
- name: set custom text
  include: motd.yml
- name: install packages
  include: packages.yml

$ cat prod.yml
---
- hosts: all
  become: yes
  roles:
    - base

- hosts: web
  become: yes
  roles:
    - httpd
----
Run the playbook!
[shell]
----
$ ansible-playbook prod.yml
----

[NOTE]
====
Take notice of the different content of `/etc/motd` on the control node!
====
=====

.Solution 5
[%collapsible]
====
[shell]
----
$ cat
---
dependencies:
  - base

$ cat prod.yml 
---
- hosts: web
  become: yes
  roles:
    - httpd

$ ansible-playbook prod.yml
----
====
