# LAB05.2 - Ansible Roles - Handlers and Blocks

We start to use handlers and blocks as well.

### TASK 1
- Create a playbook `myhandler.yml` which uses a role `handlerrole`.
- The role `handlerrole` should do the following:
- Create a directory `newdir` in the folder `/home/ansible`.
- If the folder didn't exist before, then do create a file `README.TXT` in this folder containing the text "This folder was created at <timestamp>"
- The value of timestamp should contain a quite accurate timestamp of when `ansible-playbook` was run.
- Run the playbook several times on node1 to see if it is really idempotent.

### Task 2
- Write a `download.yml` playbook which runs a role `downloader`.
- The role `downloader` should try to download a file from a non-existing URL.
- The playbook should be able to handle errors. Make the playbook output the message _"Download failed!"_ if
  the `download` task failed. The playbook must keep on running and shall not exit after this message.
- In all cases, output a message at the end of the play informing you the download attempt has finished.
- Use a Block.


## Solutions

.Solution 1
[%collapsible]
====
Below is a possible solution:

[shell]
----
$ cat myhandler.yml
- hosts: node1
  become: yes
  roles:
    - handerrole

$ cat roles/handlerrole/tasks/main.yml
---
- name: create directory
  file:
    path: /home/ansible/newdir
    state: directory
  notify: timestamp

$ cat roles/handlerrole/handlers/main.yml
---
- name: create readme with timestamp 
  copy:
    dest: /home/ansible/techlab/newdir/README.TXT
    content: "This folder was created at {{ ansible_date_time.iso8601 }}"    
  listen: timestamp
----
====

.Solution 2
[%collapsible]
====
[shell]
----
$ cat download.yml
---
- hosts: node2
  become: yes
  tasks:
    - block:
        - name: Download things from the internet
          get_url:
            url: http://www.asdfasdfasppppakdd.com/file
            dest: /tmp/
      rescue:
        - debug:
            msg: "Download failed!"
      always:
        - debug:
            msg: "Download attempt finished."

$ ansible-playbook download.yml
----
====
