# LAB04.1 - Ansible Playbooks - Basics

In this lab we'll get used to writing and running ansible playbooks.

### Task 1
Create a playbook `webserver.yml` which does the following:

- Install `httpd` on the nodes in the `web` group.
- Start `httpd` and ensure the service starts on boot. Ensure that the firewall is also started and enabled.
- Ensure port 80 is open on the firewall.

[TIP]
====
 Check what the options "immediate" and "permanent" of the service module mean and do.
====

- Run the playbook. After completion test if the `httpd.service` is running and enabled on node1.

### TASK 2
- Create a folder `/home/ansible/techlab/inventory` and move your inventory file `hosts` there.
- Configure ansible to use `/home/ansible/techlab/inventory/hosts` as the default inventory. Do this using a configuration file in the `/home/ansible/techlab/` directory. 
- Run the playbook `webserver.yml` again without using the `-i` flag to see if the configuration works.

### TASK 3
- Add intentionally errors to your plabook and have a look at the output. You should get a feeling for errormessages.
- add a wrong intendation. Remember that this is a common mistake! 
- add a wrong parameter name
- Remove the mistakes

[TIP]
====
Remember `loop:` or `with_items:`
====

## Solutions

.Solution 1
[%collapsible]
====
Below is a possible solution for your playbook: 

[shell]
----
---
- hosts: web
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: open firewall for http
      firewalld:
       service: http
       state: enabled
       permanent: yes
       immediate: yes
----

Run your playbook with:

[shell]
----
$ ansible-playbook -i hosts webserver.yml
----

Check `httpd.service` on node 1:

[shell]
----
$ systemctl status httpd.service 
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-11-01 13:44:25 CET; 2min 41s ago
     Docs: man:httpd(8)
...
...
====

.Solution 2
[%collapsible]
====
Copy the default ansible.cfg to your directory:
[shell]
----
$ mkdir /home/ansible/techlab/inventory
$ mv /home/ansible/techlab/hosts /home/ansible/techlab/inventory
$ cp /etc/ansible/ansible.cfg /home/ansible/techlab/
----

Edit your `ansible.cfg` file. Uncomment and edit the "inventory" entry to use your file:
[shell]
----
...
[defaults]
# some basic default values...
inventory      = /home/ansible/techlab/inventory/hosts # <-- edit this line
#library        = /usr/share/my_modules/
...
----

[shell]
----
$ ansible-playbook webserver.yml
PLAY [web] ***********************************************************************

TASK [Gathering Facts] ***********************************************************
ok: [node1]

TASK [install httpd] *************************************************************
ok: [node1]
...
----
====

.Solution 3
[%collapsible]
====
Wrong intendation:
[shell]
----
---
- hosts: web
  become: yes
  tasks:
    - name: install httpd
      yum:
      name: httpd	# <-- wrong intendation
      state: installed  # <-- wrong intendation
----

Wrong parameter name:
[shell]
----
---
- hosts: web
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
        enabled: yes     # <-- doesn't exist for yum module
----

====
