# LAB04 - Ansible Playbooks

In this lab we'll get more used to using playbooks and learn something about handlers.

### Task 1
Create a playbook `myhandler.yml` which does the following:
- Create a directory `newdir` in the techlab folder of node1.
- if the folder didn't exist before, then do create a file `README.TXT` in this folder containing the text "This folder was created at <timestamp>"
- the value of timestamp should contain a quite accurate timestamo of when ansible-playbook was run.
- run the playbook several time to see if it is really idempotent.

[TIP]
====
 Remember to use facts. Be aware that there is not one single valid solution. Do decide yourself what you think solves the problem best.
====

### TASK 2
- Create a folder `inventory` and move your inventory `hosts` there.
- Configure ansible to use `/home/ansible/techlab/inventory/hosts` as the default inventory. Do this using a configuration file in the `/home/ansible/techlab/` directory. 
- Run the playbook again without using the `-i` flag to see if the configuration works.

## Solutions

.Solution 1
[%collapsible]
====
Below is a possible solution for your playbook: 

[shell]
----
---
- hosts: node1
  become: yes
  tasks:
    - name: create directory
      file:
        path: /home/ansible/techlab/newdir
        state: directory
      notify: timestamp

  handlers:
    - name: create readme with timestamp 
      copy:
        dest: /home/ansible/techlab/newdir/README.TXT
        content: "This folder was created at {{ ansible_date_time.iso8601 }}"    
      listen: timestamp
----

If you are unsure how to run your playbook, then have a look at the earlier labs.



.Solution 2
[%collapsible]
====
[shell]
----
$ mkdir inventory; mv hosts inventory/hosts
$ cp /etc/ansible/ansible.cfg /home/ansible/techlab/
----

