# LAB04 - Ansible Playbooks

In this lab we'll get more used to using playbooks.

### Task 1
- Create a playbook `myhandler.yml` which does the following:
- Create a directory `newdir` in the folder `/home/ansible` of node1.
- if the folder didn't exist before, then do create a file `README.TXT` in this folder containing the text "This folder was created at <timestamp>"
- the value of timestamp should contain a quite accurate timestamp of when `ansible-playbook` was run.
- run the playbook several times to see if it is really idempotent.

[TIP]
====
 Remember to use facts. Be aware that there is not one single valid solution. Do decide yourself what you think solves the problem best.
====

### TASK 2
- Do extend your playbook to do the following:
- If the uptime of the server is higher than one hour, then do reboot the server.

## Solutions

.Solution 1
[%collapsible]
====
Below is a possible solution for your playbook: 

[shell]
----
---
- hosts: node1
  become: yes
  tasks:
    - name: create directory
      file:
        path: /home/ansible/newdir
        state: directory
      notify: timestamp

  handlers:
    - name: create readme with timestamp 
      copy:
        dest: /home/ansible/techlab/newdir/README.TXT
        content: "This folder was created at {{ ansible_date_time.iso8601 }}"    
      listen: timestamp
----

If you are unsure how to run your playbook, then have a look at the earlier labs.
====


.Solution 2
[%collapsible]
====
Add the following task to your play
[shell]
----
    - name: reboot if longer than one hour up
      reboot:
      when: ansible_uptime_seconds >= '3600'
----
====
